### ISSUE TITLE
can't run command juicer and juicer-admin 

### ISSUE THREAD

**Issue by pkhadka56** [juicer/juicer#233]
mongodb v3.0.12
-----------------------------
pulp v2.8.3
-----------------------------

\# vi /etc/yum.repos.d/juicer.repo
[juicer]
name=Juicer Public Repository
baseurl=http://tbielawa.fedorapeople.org/juicer/
enabled=1
gpgcheck=0

\# yum install juicer juicer-admin -y
\# juicer 
Traceback (most recent call last):
  File "/bin/juicer", line 19, in <module>
    import juicer.juicer
  File "/usr/lib/python2.7/site-packages/juicer/juicer/__init__.py", line 18, in <module>
    import juicer.utils.Log
  File "/usr/lib/python2.7/site-packages/juicer/utils/__init__.py", line 44, in <module>
    from pymongo import Connection as MongoClient
ImportError: cannot import name Connection

\# juicer-admin
Traceback (most recent call last):
  File "/bin/juicer-admin", line 19, in <module>
    import juicer.admin.Parser
  File "/usr/lib/python2.7/site-packages/juicer/admin/__init__.py", line 18, in <module>
    from juicer.admin.JuicerAdmin import JuicerAdmin as ja
  File "/usr/lib/python2.7/site-packages/juicer/admin/JuicerAdmin.py", line 21, in <module>
    import juicer.utils
  File "/usr/lib/python2.7/site-packages/juicer/utils/__init__.py", line 44, in <module>
    from pymongo import Connection as MongoClient
ImportError: cannot import name Connection

**Comment by pkhadka56** [comment]
solved with following command:

\# pip install pymongo==2.7.2
